In [3]:
import torch

# Create a 4x4 matrix of float32 with all elements as 1
tensor = torch.ones((4, 4), dtype=torch.float32)

# Modify the middle 2x2 matrices to 2
tensor[1:3, 1:3] = 2

print(tensor)


tensor([[1., 1., 1., 1.],
        [1., 2., 2., 1.],
        [1., 2., 2., 1.],
        [1., 1., 1., 1.]])


In [4]:
import torch
from torch.autograd import Variable

# Define the function y = x^2
x = Variable(torch.FloatTensor([2]), requires_grad=True)
y = x**2

# Compute the derivative
y.backward()

# Print the derivative
print(x.grad)


tensor([4.])


In [5]:
import torch
from torch.autograd import Variable

# Define the variables
x = Variable(torch.FloatTensor([2, 3]), requires_grad=True)

# Define k
k0 = x[0]**2 + 3*x[1]
k1 = 2*x[0] + x[1]**2
k = torch.stack([k0, k1])

# Compute the derivative
k.backward(torch.FloatTensor([1, 0]), retain_graph=True)
dk_dx0 = x.grad.clone()
x.grad.data.zero_()

k.backward(torch.FloatTensor([0, 1]))
dk_dx1 = x.grad.clone()

print(torch.stack([dk_dx0, dk_dx1]))


tensor([[4., 3.],
        [2., 6.]])


In [9]:
import torch.nn as nn
import torch.nn.init as init

def xavier_init(layer):
    if isinstance(layer, nn.Linear):
        size_in, size_out = layer.weight.size()
        xavier_stddev = 1. / torch.sqrt(torch.Tensor([size_in + size_out]) / 2.)
        init.uniform_(layer.weight, -xavier_stddev.item(), xavier_stddev.item())
        init.constant_(layer.bias, 0)

# Example usage in a neural network model
class MyModel(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(MyModel, self).__init__()
        self.fc1 = nn.Linear(in_features=input_size, out_features=hidden_size)
        self.fc2 = nn.Linear(in_features=hidden_size, out_features=output_size)
        # Call the xavier_init function for each linear layer
        xavier_init(self.fc1)
        xavier_init(self.fc2)

# Instantiate the model with your specific input, hidden, and output sizes
input_size = 10  # Replace with your input size
hidden_size = 20  # Replace with your hidden layer size
output_size = 5   # Replace with your output size
model = MyModel(input_size, hidden_size, output_size)
# Print initialized weights and biases
for name, param in model.named_parameters():
    print(f"{name}: {param}")

fc1.weight: Parameter containing:
tensor([[-0.1172,  0.1092,  0.0051,  0.0197,  0.0835, -0.2558, -0.2546, -0.0309,
          0.0943,  0.2141],
        [-0.0939,  0.2544,  0.1506, -0.1021,  0.0011,  0.0535, -0.2276, -0.0352,
         -0.1310, -0.2430],
        [ 0.1506, -0.1586, -0.0053,  0.0879,  0.1100,  0.1401, -0.1329,  0.0701,
          0.1184,  0.1247],
        [-0.1298,  0.1764, -0.1493, -0.1658, -0.0722,  0.1130, -0.1446,  0.2056,
          0.0876,  0.0104],
        [-0.0113, -0.1321,  0.2575,  0.1681,  0.1869,  0.2474,  0.1777,  0.1096,
          0.0029,  0.1148],
        [-0.0395,  0.2361, -0.0679, -0.0034, -0.0159,  0.0711, -0.2272,  0.0170,
          0.1472, -0.0330],
        [-0.1539,  0.0893,  0.1744,  0.2548,  0.2264, -0.1973,  0.2451,  0.2243,
         -0.0203,  0.2563],
        [-0.1810,  0.2514, -0.0121, -0.2149, -0.2138, -0.1085,  0.1862,  0.0176,
          0.1989, -0.2384],
        [-0.0481,  0.0612, -0.0564,  0.0538, -0.1855, -0.0162,  0.0287,  0.0776,
          0.1